### ISSUE TITLE
IOError at /shapefile/map-it

### ISSUE THREAD

**Issue by umuchlish** [IQSS/geoconnect#108]
Got error: 

IOError at /shapefile/map-it/ea67f6661788fb557174c6123ac2f9b1db87a5c01871bb7b5e4aa98aac318900/

With dataverse 4.2.4  {
What the step to acquire the cga-worldmap api-token to store at ../settings/worldmap_secrets_dev.json?
What the step to store dataverse api-token and where?
Does shared-dataverse-information need to configure also?
}

vagrant (stage1.sh) failed to create file in webapps on line 38 and no file to copy at line 45;

**Comment by raprasad** [comment]
@umuchlish, your dataverse connection can use the existing geoconnect at http://geoconnect.datascience.iq.harvard.edu/
e.g., Currently geoconnect isn't useful to set up on your own unless you're also running WorldMap.

**Comment by umuchlish** [comment]
I have used default config but failed to display with following message: 
"Sorry! This request is not from a Dataverse registered to use the WorldMap.
This dataverse url was not recognized: https://data.my.org/dataset.xhtml?id=3&versionId2"

I am also installed cga-worldmap, but difficult to found its Token generation from worldmap.

**Comment by raprasad** [comment]
Hi Usman,

I added your url to the list of “registered dataverses” within the running geoconnect.

For further troubleshooting, please feel free to email me directly at raman_prasad@harvard.edu<mailto:raman_prasad@harvard.edu>





On Feb 23, 2016, at 7:37 PM, Usman Muchlish <notifications@github.com<mailto:notifications@github.com>> wrote:

 https://data.my.org/dataset.xhtml?id=3&versionId2<https://urldefense.proofpoint.com/v2/url?u=https-3A__data.my.org_dataset.xhtml-3Fid-3D3-26versionId2&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=EkFi6BF7pof1mvmoyqcphtSeruEfuDmHCUNhyy4Y_XM&m=7dwgiQaysQjTKUjrNKGT6JAsX1P1vqsdD8lswDtIdG0&s=v4YIH0QtUIlchMsoTQV5y732dEISJfV7Xmo2czkkqbc&e=>

**Comment by pdurbin** [comment]
@raprasad FYI that you could grab @umuchlish 's existing ticket at https://help.hmdc.harvard.edu/Ticket/Display.html?id=232956 if that's a better place than here for this.

**Comment by umuchlish** [comment]
Hi Prasad, thank you for your response, Durbin is right, those message has filtered to public. I have send the request in term of connect to official-geoconnect. 

I have been challenged to make local version of worldmap-geoconnect-dataverse for our low-bandwidth office. 

Thank you guys.
Cheers
Usman
